### ISSUE TITLE
Create anaconda environment files for python projects

### ISSUE THREAD

**Issue by nitred** [ansrivas/protemplates#12]
My use case involves creating python projects in the data science domain which I would like to eventually dockerize. Since protemplates works on the assumption that python projects are being developed using virtualenvs (of any kind) and since arguably the best virtualenv and package manager for data science is Anaconda, it would be great to have support for anaconda environment files.

The additions I would like to have are the following:

1. An `environment.yml` or `dev_environment.yml` file at the root of the project. An example of an environment file looks like the following.
```
name: PROJECT_NAME
channels:
  - defaults
dependencies:
- python=PYTHON_VERSION
- pip:
    - future
```

2. The `README.md` file can be updated with the following command to create an environment from the environment file:
```
conda env create --force -f dev_environment.yml
source activate PROJECT_NAME
```

3. (OPTIONAL) Create a new category of protemplates project languages called `python-anaconda` so that we can separate regular python projects from anaconda python projects.

**Comment by ansrivas** [comment]
fixed in acdf19c
